#!/usr/bin/env python3
"""Run a small Yosys synthesis flow and summarize hardware cost."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path
from typing import Any


VERILOG_SUFFIXES = {".v", ".sv", ".vh", ".svh"}


def collect_verilog(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for path in paths:
        if path.is_dir():
            files.extend(
                p for p in sorted(path.rglob("*")) if p.is_file() and p.suffix in VERILOG_SUFFIXES
            )
        elif path.is_file():
            files.append(path)
        else:
            raise FileNotFoundError(path)
    if not files:
        raise SystemExit("No Verilog/SystemVerilog files found.")
    return files


def yosys_quote(path: Path) -> str:
    return '"' + str(path).replace("\\", "\\\\").replace('"', '\\"') + '"'


def synth_command(mode: str, top: str, flatten: bool, abc: bool) -> list[str]:
    if mode == "xilinx":
        args = ["synth_xilinx", "-top", top]
        if flatten:
            args.append("-flatten")
        return [" ".join(args)]
    if mode == "ice40":
        args = ["synth_ice40", "-top", top]
        if not abc:
            args.append("-noabc")
        return [" ".join(args)]
    if mode == "ecp5":
        args = ["synth_ecp5", "-top", top]
        if not abc:
            args.append("-noabc")
        return [" ".join(args)]

    cmd = [
        f"hierarchy -check -top {top}",
        "proc",
        "opt",
        "fsm",
        "opt",
        "memory",
        "opt",
        "techmap",
        "opt",
    ]
    if abc:
        cmd.extend(["abc -fast", "opt"])
    if flatten:
        cmd.extend(["flatten", "opt"])
    cmd.extend(["clean", "check"])
    return cmd


def build_yosys_script(
    files: list[Path],
    top: str,
    out_dir: Path,
    mode: str,
    flatten: bool,
    abc: bool,
) -> str:
    lines = ["# Auto-generated by cfu-designer/scripts/yosys_cost_report.py"]
    for file in files:
        lines.append(f"read_verilog -sv {yosys_quote(file)}")
    lines.extend(synth_command(mode, top, flatten, abc))
    lines.append(f"tee -o {yosys_quote(out_dir / 'stat.txt')} stat -top {top}")
    lines.append(f"tee -o {yosys_quote(out_dir / 'stat.json')} stat -json -top {top}")
    lines.append(f"write_json {yosys_quote(out_dir / 'netlist.json')}")
    return "\n".join(lines) + "\n"


def parse_text_stat(text: str) -> dict[str, Any]:
    metrics: dict[str, Any] = {
        "num_wires": None,
        "num_wire_bits": None,
        "num_public_wires": None,
        "num_public_wire_bits": None,
        "num_memories": None,
        "num_memory_bits": None,
        "num_processes": None,
        "num_cells": None,
        "cell_counts": {},
        "estimated_lut4": None,
    }
    keys = {
        "Number of wires:": "num_wires",
        "Number of wire bits:": "num_wire_bits",
        "Number of public wires:": "num_public_wires",
        "Number of public wire bits:": "num_public_wire_bits",
        "Number of memories:": "num_memories",
        "Number of memory bits:": "num_memory_bits",
        "Number of processes:": "num_processes",
        "Number of cells:": "num_cells",
    }
    for line in text.splitlines():
        stripped = line.strip()
        for prefix, key in keys.items():
            if stripped.startswith(prefix):
                metrics[key] = int(stripped.split()[-1])
        match = re.match(r"^\s+(\S+)\s+(\d+)\s*$", line)
        if match:
            cell, count = match.groups()
            if cell.startswith("$") or cell[0].isalpha() or cell[0] == "_":
                metrics["cell_counts"][cell] = int(count)
        if stripped.startswith("Estimated number of LCs:"):
            metrics["estimated_lut4"] = int(stripped.split()[-1])
    return metrics


def load_json_stat(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError:
        return None
    return data


def metrics_from_json_stat(data: dict[str, Any] | None, top: str) -> dict[str, Any] | None:
    if not data:
        return None
    modules = data.get("modules", {})
    module = modules.get("\\" + top) or modules.get(top) or data.get("design")
    if not isinstance(module, dict):
        return None
    return {
        "num_wires": module.get("num_wires"),
        "num_wire_bits": module.get("num_wire_bits"),
        "num_public_wires": module.get("num_pub_wires"),
        "num_public_wire_bits": module.get("num_pub_wire_bits"),
        "num_memories": module.get("num_memories"),
        "num_memory_bits": module.get("num_memory_bits"),
        "num_processes": module.get("num_processes"),
        "num_cells": module.get("num_cells"),
        "cell_counts": module.get("num_cells_by_type", {}),
        "estimated_lut4": None,
    }


def write_reports(
    out_dir: Path,
    top: str,
    files: list[Path],
    mode: str,
    flatten: bool,
    abc: bool,
    metrics: dict[str, Any],
    json_stat: dict[str, Any] | None,
) -> None:
    summary = {
        "top": top,
        "mode": mode,
        "flatten": flatten,
        "abc": abc,
        "files": [str(p) for p in files],
        "metrics": metrics,
        "yosys_stat_json_available": json_stat is not None,
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")

    cell_counts = metrics.get("cell_counts", {})
    top_cells = sorted(cell_counts.items(), key=lambda item: (-item[1], item[0]))[:20]
    lines = [
        f"# Yosys Cost Report: `{top}`",
        "",
        f"- Mode: `{mode}`",
        f"- Flatten: `{flatten}`",
        f"- ABC: `{abc}`",
        f"- Verilog files: `{len(files)}`",
        f"- Wires: `{metrics.get('num_wires')}`",
        f"- Wire bits: `{metrics.get('num_wire_bits')}`",
        f"- Memories: `{metrics.get('num_memories')}`",
        f"- Memory bits: `{metrics.get('num_memory_bits')}`",
        f"- Cells: `{metrics.get('num_cells')}`",
    ]
    if metrics.get("estimated_lut4") is not None:
        lines.append(f"- Estimated LUT4/LC: `{metrics.get('estimated_lut4')}`")
    lines.extend(["", "## Top Cell Types", "", "| Cell | Count |", "| --- | ---: |"])
    for cell, count in top_cells:
        lines.append(f"| `{cell}` | {count} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- Use this as a fast relative cost proxy for CFU design iteration.",
            "- Compare the same top module, Yosys mode, flatten setting, and generated RTL style across variants.",
            "- Use FPGA/vendor synthesis for final LUT/FF/BRAM/Fmax claims.",
        ]
    )
    (out_dir / "summary.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Estimate Verilog hardware cost with Yosys.")
    parser.add_argument("verilog", nargs="+", type=Path, help="Verilog files or directories.")
    parser.add_argument("--top", required=True, help="Top module name.")
    parser.add_argument("--out-dir", type=Path, default=None, help="Output directory.")
    parser.add_argument(
        "--mode",
        choices=["generic", "xilinx", "ice40", "ecp5"],
        default="generic",
        help="Synthesis flow. Use generic for technology-independent CFU comparison.",
    )
    parser.add_argument("--flatten", action="store_true", help="Flatten hierarchy before reporting.")
    parser.add_argument("--no-abc", action="store_true", help="Skip ABC mapping when supported.")
    parser.add_argument("--yosys", default="yosys", help="Yosys executable.")
    args = parser.parse_args()

    files = collect_verilog(args.verilog)
    out_dir = args.out_dir or Path("yosys_cost") / args.top
    out_dir.mkdir(parents=True, exist_ok=True)

    abc = not args.no_abc
    script = build_yosys_script(files, args.top, out_dir, args.mode, args.flatten, abc)
    script_path = out_dir / "run.ys"
    script_path.write_text(script)

    log_path = out_dir / "yosys.log"
    proc = subprocess.run(
        [args.yosys, "-s", str(script_path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    log_path.write_text(proc.stdout)
    if proc.returncode != 0:
        raise SystemExit(f"Yosys failed with exit code {proc.returncode}; see {log_path}")

    stat_text_path = out_dir / "stat.txt"
    json_stat = load_json_stat(out_dir / "stat.json")
    metrics = metrics_from_json_stat(json_stat, args.top)
    if metrics is None:
        metrics = parse_text_stat(stat_text_path.read_text() if stat_text_path.exists() else proc.stdout)
    write_reports(out_dir, args.top, files, args.mode, args.flatten, abc, metrics, json_stat)

    print(f"Wrote {out_dir / 'summary.md'}")
    print(
        "cost top={top} cells={cells} wire_bits={bits} memories={mem} memory_bits={mbits}".format(
            top=args.top,
            cells=metrics.get("num_cells"),
            bits=metrics.get("num_wire_bits"),
            mem=metrics.get("num_memories"),
            mbits=metrics.get("num_memory_bits"),
        )
    )


if __name__ == "__main__":
    main()
